### ISSUE TITLE
Scraps reaches ratelimit on the raffles page

### ISSUE THREAD

**Issue by Sweaver273** [depthbomb/Scraps#1]
When running the program for an extensive period of time, it ends up refreshing the raffles page too much and triggers a ratelimit as seen here: https://i.imgur.com/7JMPW5e.png

**Comment by depthbomb** [comment]
This is normal and can't be worked around without adding a huge delay between loading raffles.
The program is still able to load and join raffles despite that error, and you can still access raffles you've won by clicking them from the notifications menu when logged in.

**Comment by Sweaver273** [comment]
Oh nevermind - I just experienced an error on my end and thought it was due to the ratelimit, thanks for the info!
