### ISSUE TITLE
Issue when idling

### ISSUE THREAD

**Issue by ashprids** [depthbomb/Scraps#11]
Sometimes when the program runs for a while and it finishes signing up for all raffles, the console will say "Stopping" and then say "Start" without saying it has stopped. The only way to fix this is to close and reopen, but this makes it inefficient for idling for long periods at a time.

Also it would be cool if there's a way to make the program run when the computer is in sleep mode.
(This is happening on Windows exe BTW, not sure about other formats)

**Comment by Celdri** [comment]
It stops because your internet disconnects. Also, Windows pauses all apps on sleep mode, so it is impossible to keep it running on sleep mode.

**Comment by ghost** [comment]
same

**Comment by ghost** [comment]
it automatically stops

**Comment by ashprids** [comment]
Happens due to internet cuts, if you're on WiFi.
