### ISSUE TITLE
Launch on startup option

### ISSUE THREAD

**Issue by poopslayer4000** [depthbomb/Scraps#12]
Add the option to make it launch on startup

**Comment by depthbomb** [comment]
You can do this with the included CLI version **Scraps.exe**.

1. Launch it first to generate its config file at `My Documents\Caprine Logic\Scraps\Config.json`
2. Fill out the config file
3. Create a shortcut to **Scraps.exe** and place it in `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp`
