### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by YGT72** [depthbomb/Scraps#13]
Pls make it so u can put multiple scrap.tf accounts in 1 go to farm items and sometimes the program auto stops so if u can fix it that would be nice thank you

**Comment by depthbomb** [comment]
Multiple accounts cannot be used since your IP is tied to raffles you joined.

**Comment by YGT72** [comment]
What about using proxys

**Comment by depthbomb** [comment]
The console version of Scraps included with the GUI version has basic HTTP proxy support, more info can be read about [here](https://github.com/depthbomb/Scraps/blob/master/SETTINGS.md).

There are no plans to implement this into the GUI version at the moment.

**Comment by YGT72** [comment]
Ok thx for telling
