### ISSUE TITLE
Cant get proxies to work

### ISSUE THREAD

**Issue by copium4352** [depthbomb/Scraps#15]
How to do i use proxies?
I tried using it - 

{
  "Version": 13,
  "Cookie": "random cookie here!",
  "JoinNewestFirst": true,
  "Paranoid": true,
  "Delays": {
    "IncrementScanDelay": true,
    "ScanDelay": 5000,
    "PaginateDelay": 500,
    "JoinDelay": 4000
  },
  "Proxies": [138.68.235.51:80]
}

but it gives error. That proxy i got from proxyscrape
Also how to i give it a list of proxies to use?

**Comment by depthbomb** [comment]
Make sure to wrap each proxy in quotes in the array.
