### ISSUE TITLE
Error stopping program

### ISSUE THREAD

**Issue by Barmem** [depthbomb/Scraps#18]
Started frequently getting this error
`02:34:06 System.NullReferenceException: Object reference not set to an instance of an object.
   at Scraps.GUI.Services.RaffleService.ScanRafflesAsync()
   at Scraps.GUI.Services.RaffleService.StartAsync()Object reference not set to an instance of an object.
`
and pressing "Won raffles button gives this error message
`System.Runtime.InteropServices.COMException (0x80010106): Изменение режима для потока после его установки невозможно. (0x80010106 (RPC_E_CHANGED_MODE))
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync(String browserExecutableFolder, String userDataFolder, CoreWebView2EnvironmentOptions options)
   at Scraps.GUI.Forms.WebViewForm.InitializeBrowserAsync(String url, String cookies)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

************** Загруженные сборки **************
System.Private.CoreLib
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Private.CoreLib.dll
----------------------------------------
Scraps.GUI
    Версия сборки: 4.5.0.1
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.Runtime
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Runtime.dll
----------------------------------------
System.Windows.Forms
    Версия сборки: 6.0.1.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/System.Windows.Forms.dll
----------------------------------------
System.ComponentModel.Primitives
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.ComponentModel.Primitives.dll
----------------------------------------
System.Windows.Forms.Primitives
    Версия сборки: 6.0.1.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/System.Windows.Forms.Primitives.dll
----------------------------------------
System.Runtime.InteropServices
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Runtime.InteropServices.dll
----------------------------------------
System.Drawing.Primitives
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Drawing.Primitives.dll
----------------------------------------
System.Collections.Specialized
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Collections.Specialized.dll
----------------------------------------
System.Threading
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Threading.dll
----------------------------------------
System.Configuration.ConfigurationManager
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/System.Configuration.ConfigurationManager.dll
----------------------------------------
System.ObjectModel
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.ObjectModel.dll
----------------------------------------
System.Linq
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Linq.dll
----------------------------------------
System.Collections
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Collections.dll
----------------------------------------
System.Private.Uri
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Private.Uri.dll
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
System.Diagnostics.Process
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Diagnostics.Process.dll
----------------------------------------
System.Collections.NonGeneric
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Collections.NonGeneric.dll
----------------------------------------
Microsoft.Win32.Primitives
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/Microsoft.Win32.Primitives.dll
----------------------------------------
System.Memory
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Memory.dll
----------------------------------------
System.Security.Cryptography.Algorithms
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Security.Cryptography.Algorithms.dll
----------------------------------------
System.Security.Cryptography.Primitives
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Security.Cryptography.Primitives.dll
----------------------------------------
System.ComponentModel.TypeConverter
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.ComponentModel.TypeConverter.dll
----------------------------------------
System.Xml.ReaderWriter
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Xml.ReaderWriter.dll
----------------------------------------
System.Private.Xml
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Private.Xml.dll
----------------------------------------
System.Text.RegularExpressions
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Text.RegularExpressions.dll
----------------------------------------
System.Net.WebClient
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Net.WebClient.dll
----------------------------------------
System.ComponentModel.EventBasedAsync
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.ComponentModel.EventBasedAsync.dll
----------------------------------------
System.Text.Encoding.Extensions
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Text.Encoding.Extensions.dll
----------------------------------------
System.Threading.Thread
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Threading.Thread.dll
----------------------------------------
System.Runtime.Serialization.Formatters
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Runtime.Serialization.Formatters.dll
----------------------------------------
System.Xml.XmlSerializer
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Xml.XmlSerializer.dll
----------------------------------------
System.Drawing.Common
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/System.Drawing.Common.dll
----------------------------------------
System.Diagnostics.TraceSource
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Diagnostics.TraceSource.dll
----------------------------------------
NLog
    Версия сборки: 4.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
netstandard
    Версия сборки: 2.1.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/netstandard.dll
----------------------------------------
System.Net.Http
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Net.Http.dll
----------------------------------------
System.Diagnostics.StackTrace
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Diagnostics.StackTrace.dll
----------------------------------------
System.Net.Primitives
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Net.Primitives.dll
----------------------------------------
System.Diagnostics.Tracing
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Diagnostics.Tracing.dll
----------------------------------------
System.Diagnostics.DiagnosticSource
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Diagnostics.DiagnosticSource.dll
----------------------------------------
System.Net.Security
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Net.Security.dll
----------------------------------------
System.Security.Cryptography.X509Certificates
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Security.Cryptography.X509Certificates.dll
----------------------------------------
System.Text.Json
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Text.Json.dll
----------------------------------------
System.Collections.Concurrent
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Collections.Concurrent.dll
----------------------------------------
System.Net.Sockets
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Net.Sockets.dll
----------------------------------------
System.Threading.Overlapped
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Threading.Overlapped.dll
----------------------------------------
System.Net.NameResolution
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Net.NameResolution.dll
----------------------------------------
System.Threading.ThreadPool
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Threading.ThreadPool.dll
----------------------------------------
System.Security.Principal.Windows
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Security.Principal.Windows.dll
----------------------------------------
System.Security.Claims
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Security.Claims.dll
----------------------------------------
System.Security.Cryptography.Encoding
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Security.Cryptography.Encoding.dll
----------------------------------------
System.Reflection.Emit.Lightweight
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Reflection.Emit.Lightweight.dll
----------------------------------------
System.Reflection.Primitives
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Reflection.Primitives.dll
----------------------------------------
System.Reflection.Emit.ILGeneration
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Reflection.Emit.ILGeneration.dll
----------------------------------------
System.Text.Encodings.Web
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Text.Encodings.Web.dll
----------------------------------------
System.Runtime.Intrinsics
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Runtime.Intrinsics.dll
----------------------------------------
System.Numerics.Vectors
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Numerics.Vectors.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Runtime.CompilerServices.Unsafe.dll
----------------------------------------
Microsoft.Toolkit.Uwp.Notifications
    Версия сборки: 7.1.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
Accessibility
    Версия сборки: 4.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/Accessibility.dll
----------------------------------------
Microsoft.Win32.SystemEvents
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/Microsoft.Win32.SystemEvents.dll
----------------------------------------
System.ComponentModel
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.ComponentModel.dll
----------------------------------------
System.Diagnostics.FileVersionInfo
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Diagnostics.FileVersionInfo.dll
----------------------------------------
System.Resources.Extensions
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/System.Resources.Extensions.dll
----------------------------------------
System.Drawing
    Версия сборки: 6.0.1.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/System.Drawing.dll
----------------------------------------
System.Data.Common
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Data.Common.dll
----------------------------------------
System.Net.Mail
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Net.Mail.dll
----------------------------------------
System.IO.FileSystem.Watcher
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.IO.FileSystem.Watcher.dll
----------------------------------------
System.Linq.Expressions
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Linq.Expressions.dll
----------------------------------------
HtmlAgilityPack
    Версия сборки: 1.11.40.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
Microsoft.Win32.Registry
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/Microsoft.Win32.Registry.dll
----------------------------------------
Microsoft.Windows.SDK.NET
    Версия сборки: 10.0.17763.22
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
WinRT.Runtime
    Версия сборки: 1.4.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
System.IO.FileSystem
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.IO.FileSystem.dll
----------------------------------------
System.Reflection.Emit
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Reflection.Emit.dll
----------------------------------------
DynamicComActivator
    Версия сборки: 0.0.0.0
    Версия Win32: неприменимо
    CodeBase (база кода): file:///C:/Users/Barmem/AppData/Local/Programs/Caprine%20Logic/Scraps/Microsoft.Toolkit.Uwp.Notifications.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Версия сборки: 0.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Private.CoreLib.dll
----------------------------------------
System.Text.Encoding.CodePages
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Text.Encoding.CodePages.dll
----------------------------------------
System.Reflection.Metadata
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Reflection.Metadata.dll
----------------------------------------
System.Collections.Immutable
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Collections.Immutable.dll
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Версия сборки: 1.0.1072.54
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
Microsoft.Web.WebView2.Core
    Версия сборки: 1.0.1072.54
    Версия Win32: неприменимо
    CodeBase (база кода): 
----------------------------------------
mscorlib
    Версия сборки: 4.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/mscorlib.dll
----------------------------------------
System
    Версия сборки: 4.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.dll
----------------------------------------
System.Runtime.Loader
    Версия сборки: 6.0.0.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.NETCore.App/6.0.1/System.Runtime.Loader.dll
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 6.0.1.0
    Версия Win32: 6.0.121.56705
    CodeBase (база кода): file:///C:/Program%20Files/dotnet/shared/Microsoft.WindowsDesktop.App/6.0.1/ru/System.Windows.Forms.resources.dll
----------------------------------------

************** Оперативная отладка (JIT) **************

`

**Comment by Barmem** [comment]
?

**Comment by depthbomb** [comment]
This issue is closed because it is a duplicate. #19 will be the active issue.

**Comment by Barmem** [comment]
oh, weird, have no idea why 2 got submitted
