### ISSUE TITLE
Suggestion : )

### ISSUE THREAD

**Issue by Dragon123cz** [depthbomb/Scraps#22]
Add TimeLeft Option to Scraps, Thanks.

**Comment by depthbomb** [comment]
Could you elaborate on what this feature would do?

**Comment by Dragon123cz** [comment]
Sorry for too late reply,
I think if u add new option next to "Join newer raffle first", that will
Join raffle by time left.
I think it will be more effective.

Dne pá 4. 2. 2022 21:47 uživatel depthbomb ***@***.***>
napsal:

**Comment by depthbomb** [comment]
This is the behavior if you uncheck "Join newer raffles first".
