### ISSUE TITLE
[Suggestion] Support for Mannco.Store

### ISSUE THREAD

**Issue by HakkaYoro** [depthbomb/Scraps#23]
Today they added a raffle system (in this case giveaways) similar to scrap.tf at Mannco.Store, I don't know if it would be possible to do it, but it would be a nice feature.

**Comment by ashprids** [comment]
If this was done it'd probably be best to be under a different application, separate from Scraps. Maybe if depthbomb found another developer willing to work on it, otherwise it'd be kinda time consuming for one person to work on both consistently.

**Comment by depthbomb** [comment]
It seems simple enough. This feature can be included in a future release.
