### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by poopslayer4000** [depthbomb/Scraps#27]
I have just found out that they added a captcha when you try joining a raffle. Would this stop Scraps?
![image](https://user-images.githubusercontent.com/94883999/158991364-c0f9bd47-83cf-490d-bdb0-7e10a3ab2863.png)
![image](https://user-images.githubusercontent.com/94883999/158991568-fc7972d3-2601-4271-af7a-82974561e42d.png)

**Comment by poopslayer4000** [comment]
![image](https://user-images.githubusercontent.com/94883999/158993591-e30f5f10-62c4-4b00-be58-b7a9fd18c491.png)
Sometimes it takes multiple tries for Scraps to join the raffle because of the captcha.

**Comment by bruhmomentobama** [comment]
I found a solution, this is basically a silent ban.

1st solution: Skip 1 day from joining raffles.

2nd solution: Increase/Decrease value to join/scan/paginate

3rd solution: 1st and 2nd solution alongside a VPN.

4th solution: Wait for dev to add a captcha bypass method.

**Comment by poopslayer4000** [comment]
Will try that

**Comment by poopslayer4000** [comment]
> I found a solution, this is basically a silent ban.
> 
> 1st solution: Skip 1 day from joining raffles.
> 
> 2nd solution: Increase/Decrease value to join/scan/paginate
> 
> 3rd solution: 1st and 2nd solution alongside a VPN.
> 
> 4th solution: Wait for dev to add a captcha bypass method.

Will try that

**Comment by copium4352** [comment]
BUMP 
IM ALSO HAVING THIS ISSUE 
I HAVE TO STOP THIS FOR FEW HOURS TO GET OT WORKING AGAIN AND I COME BACK TO SAME PROBLEM
I hope we get some captcha bypass/fix whatever soon
i increased the values/delays by a little bit but still getting same thing 

Thanks and i appreciate the work on this project!

**Comment by poopslayer4000** [comment]
May have found a solution
First off, Get a Free VPN Extension like TouchVPN
Try manually joining a raffle
If this message pops up then close it, and disable the VPN.
![image](https://user-images.githubusercontent.com/94883999/159167154-ec144ef3-db95-433e-8df4-8bf20b90d989.png)
Try manually joining a raffle again or use Scraps.
It should fix it.

**Comment by depthbomb** [comment]
There aren't any plans for bypassing the recaptcha as there is no simple free solution.
Avoid setting the delays lower than the default values as they shouldn't cause you to get recaptchas.
