### ISSUE TITLE
Suggestions to prevent captcha

### ISSUE THREAD

**Issue by bruhmomentobama** [depthbomb/Scraps#28]
1. Add options to "Randomize Scan Delay", "Randomize Paginate Delay" and "Randomize Join Delay". As well as include a threshold as to how little or how much the randomized value can reach.
2. Add proxies to select from or add a proxy option that allows you to insert your own proxies.
3. To be able to have multiple accounts at once, the ability to add more cookies or have a multiple account system.
4. Have a captcha bypass token box that you can fill in if you already own a captcha bypass.
5. If adding a captcha bypass token box that you can fill in is not ever going to happen, I recommend adding a macro recorder. Basically, if you're one of the unlucky few who gets the captcha, you can have the opportunity to record yourself clicking the button and clicking the captcha button, the software will record this and repeat the action, obviously this terminates the whole "Doesn't use your main browser" thing but it could be impleneted differently, i think.

**Comment by Barmem** [comment]
yea, im basically permanently on captcha now

**Comment by depthbomb** [comment]
Basic proxy support will be coming soon. (#20)
