### ISSUE TITLE
Scrap.tf Cloudflare Causes Fatal Error

### ISSUE THREAD

**Issue by Sweaver273** [depthbomb/Scraps#3]
When attempting to use Scraps (Win 10; 64-bit), it performs a GET request to https://scrap.tf/ and since Scrap.tf has cloudflare (pretty sure this was recently added, as I never encountered this issue previously), this will return a 403 Forbidden response. Since Scraps doesn't know how to handle this response, it crashes and leaves this line in the fatal log:
[FTL] Response status code does not indicate success: 403 (Forbidden).
To figure out why 403 was being returned, I debugged the response using fiddler:
![image](https://user-images.githubusercontent.com/71162829/112712158-9d982100-8e9b-11eb-9ca4-5cbfd6bf65a7.png)
It's likely that this affects all platforms, but I only tested it on 64-bit Windows 10. Also tested on a different computer with a different IP address and still had the same issue.

**Comment by depthbomb** [comment]
I am unable to replicate this on win10-x64 but I did get a 403 error when running from a Raspberry Pi 4 (linux-arm64) on the same network. I suspect that the solution is to access the site normally in your browser so it can verify you and then try the program.

**Comment by depthbomb** [comment]
I will go ahead and close this issue. Feel free to make another if the problem persists.
