### ISSUE TITLE
How can I add more accounts to the normal version of the app?

### ISSUE THREAD

**Issue by YGT72** [depthbomb/Scraps#31]
I just want to know how I could add more scrap.tf accounts to farm items more easily thanks!

**Comment by depthbomb** [comment]
Multiple accounts won't be a feature due to them being easy to detect and a raffle entry has your IP tied to it so another account of yours can't join the same raffle.

If you wish to run multiple accounts then I recommend using a VPN and a virtual machine to run another instance of Scraps.
