### ISSUE TITLE
ScrapsGUI can't be launched after all versions newer than 4.6.1.0

### ISSUE THREAD

**Issue by bruhmomentobama** [depthbomb/Scraps#33]
Hey all of these new updates arent launchable, basically the only version  that works for me rn is 4.6.1.0
All newer vers dont work
Windows 10, 64-bit
I can't get any photos of this becuase the software itself literally doesn't launch lmao.
![hoodclassic](https://user-images.githubusercontent.com/88178558/162596226-4b6371c2-187c-45e3-9232-a32c0fb99166.jpg)

**Comment by depthbomb** [comment]
Try uninstalling and installing the newest release. If that doesn't work then look in Windows Event Viewer for any logs related to Scraps.

**Comment by bruhmomentobama** [comment]
Tried uninstalling and reinstalling 3 diff times of all newer vers than 4.6.1.0
Nothing on scraps appearing in Windows Event Viewer, nothing about install failure or whatever or corruption or anything

**Comment by depthbomb** [comment]
Navigate to `C:\Users\USERNAME\AppData\Local\Caprine_Logic` and delete every folder named like **Scraps.GUI_Path_xxxx...** and then try launching Scraps again.

**Comment by bruhmomentobama** [comment]
I think that's the problem, it doesn't exist
![image](https://user-images.githubusercontent.com/88178558/162596565-df5f4ae0-a181-4832-90cc-3461031a8491.png)

**Comment by depthbomb** [comment]
That is the installation folder which is located at `C:\Users\USERNAME\AppData\Local\Programs\Caprine Logic\Scraps`

The path I mentioned is to the user configs for the various installed versions of the program.

**Comment by bruhmomentobama** [comment]
Nope nothing happened.

**Comment by depthbomb** [comment]
Look one more time in Event Viewer, just to make sure, after attempting to launch the program, specifically under `Windows Logs > Application`

**Comment by bruhmomentobama** [comment]
Faulting application name: Scraps.GUI.exe, version: 4.7.1.0, time stamp: 0x6216d2c0
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1566, time stamp: 0x0833f2d4
Exception code: 0xe0434352
Fault offset: 0x0000000000034f69
Faulting process id: 0xbc4
Faulting application start time: 0x01d84c783567913f
Faulting application path: C:\Users\user\AppData\Local\Programs\Caprine Logic\Scraps\Scraps.GUI.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 81e0eb96-fc1e-4439-891c-dc5840d57341
Faulting package full name: 
Faulting package-relative application ID: 

Application: Scraps.GUI.exe
CoreCLR Version: 6.0.121.56705
.NET Version: 6.0.1
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException: Could not load file or assembly 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Windows.Forms, Version=6.0.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
   at Scraps.GUI.Bootstrapper.Main(String[] args)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Scraps.GUI.Bootstrapper.Main(String[] args)
   at Scraps.GUI.Bootstrapper.<Main>(String[] args)

**Comment by depthbomb** [comment]
Try installing the [.NET Desktop Runtime 6.0.3](https://dotnet.microsoft.com/en-us/download/dotnet/6.0).

**Comment by bruhmomentobama** [comment]
There's your problem, you used a un-downloadable runtime to make this methinks
![image](https://user-images.githubusercontent.com/88178558/162597079-98df828d-b9c7-43da-b6e9-4ff0ede67ab6.png)

**Comment by depthbomb** [comment]
Excuse my typo, I have fixed the link.

**Comment by bruhmomentobama** [comment]
It worked thx, but I just see this Proxy thing, where do I get proxies? Do i just get random IP addresses?

**Comment by depthbomb** [comment]
I'm glad it's working.

Proxies can be used to hide your IP address when using Scraps, provide they work. You can find various lists of free proxies but those aren't guaranteed to work and using a VPN alongside Scraps is encouraged if you wish to hide your IP.

I am closing this issue now, if you have any further issues then do create a new issue.
