### ISSUE TITLE
Auto-Claim Option and Auto-Accept-Steam-Trade-Offer

### ISSUE THREAD

**Issue by bruhmomentobama** [depthbomb/Scraps#36]
Option to Auto-Claim your winnings

So basically there's this high school girl except she's got huge boo-wait, wrong message.

So if you are out at work and you don't have your pc with you or you're off on vacation in Honduras but still have your phone, having an option which basically Auto-Claims your winnings from raffles would be really useful, so then you can accept it on your phone once you get the notification, more efficient if there was also an option to accept trade offers from your computer with ScrapsGUI having a script to play and accept offers so you get the "Please confirm an action on steam" on your phone in case you didn't get the first notification.

Hope this idea gets implemented ^w^

![Concept](https://user-images.githubusercontent.com/88178558/162602084-1242e6c4-3836-430a-b372-018a7a078a3b.png)

**Comment by bruhmomentobama** [comment]
@depthbomb Pinged cus Idk if you saw this or not, sorry.

**Comment by userbanes** [comment]
i wanna know the full story of the high school lmao

**Comment by bruhmomentobama** [comment]
i got this new anime plot. basically theres this high school girl except shes got huge boobs. i mean some serious honkers. a real set of badonkers. packin some dobonhonkeros. massive dohoonkabhankoloos. big old tonhongerekoogers
