### ISSUE TITLE
Suggestion for banishing captcha into the dark realm and one more

### ISSUE THREAD

**Issue by userbanes** [depthbomb/Scraps#39]
When captcha error is present wait for (insert a long time for captcha here) so the captcha begone also default settings DO trigger captcha maybe randomizing delays and the suggested delay I mentioned
pls mannco store raffle support

**Comment by bruhmomentobama** [comment]
be a bit more details and pping depth

**Comment by userbanes** [comment]
when scraps gives the captcha error you can make it so it has a long delay before starting again and it will get rid of the captcha error just like when you pause it and start it like a half an hour later and scraps can run again but automated

**Comment by userbanes** [comment]
Also in addition to that just in case captcha does recognize the delay randomizing it would be many helpful
