### ISSUE TITLE
Not running 

### ISSUE THREAD

**Issue by PaleScribbles** [depthbomb/Scraps#4]
Hello! first of all, I added a file named Config.json in the root but the program won't run whenever I try to run it also i pasted my session. I'm sure firewall is closed and I selected x64 for my computer so what is the problem?

**Comment by depthbomb** [comment]
The config file must be located in the location that it gets generated, not in the location the executable is located. On Windows the config is generated at `Documents\Caprine Logic\Scraps`.

Please check this location for the generated config file.

**Comment by PaleScribbles** [comment]
Hey! can you tell me should I keep it in the same folder as the other file? if yes or no i tried both also "Scraps" is folder name, right?

**Comment by depthbomb** [comment]
When you launch Scraps, it will create a Config.json file located in `Documents\Caprine Logic\Scraps`, so `Documents\Caprine Logic\Scraps\Config.json`. This config file will always be created there so you can put the .exe anywhere and run it as it will look for the config file in that location.

**Comment by PaleScribbles** [comment]
Sorry but there is no any folder like that also if I create them the program suddenly opens and closes...

**Comment by depthbomb** [comment]
Try running the program as administrator and then check to see if the folders are created in your Documents folder.

**Comment by depthbomb** [comment]
I was unable to replicate the problem on v3.1.0.0. However, a new version has been released that will make Scraps look for a config file in the same folder as the executable. Please try that version.

Feel free to make another issue if you have any more problems.

**Comment by depthbomb** [comment]
Hello, I am re-opening this issue because I think I may know the problem. During the v3 rewrite I forgot to add the operation that checked and created required folders in the application's store folder.

A new release is coming shortly that should fix the problem.

**Comment by PaleScribbles** [comment]
I tried again and it still didn't work.
