### ISSUE TITLE
whi

### ISSUE THREAD

**Issue by panininis** [depthbomb/Scraps#40]
.NET installation problem
**To Reproduce**
1. Go to 'Linux OS ((ElementaryOS'
2. Click on 'Scraps'
3. Scroll down to 'Download .net'
4.Download .net
5.Goto scraps again
6.encounter install .net (dotnet command works btw)

**Comment by depthbomb** [comment]
Are you attempting to use the GUI version of Scraps?

**Comment by panininis** [comment]
Yes the .exe with wine

**Comment by depthbomb** [comment]
Scraps is only officially supported on Windows systems, as such I cannot provide assistance when attempting to run the program on unsupported systems.
