### ISSUE TITLE
Complete Rework of Scraps (Please read through and consider, depthbomb!) (Please Upvote/Bump!)

### ISSUE THREAD

**Issue by bruhmomentobama** [depthbomb/Scraps#44]
I did some brainstorming, it seems the majority of the time whenever Scraps gets the Red Wall Of Text (Petition to make "RWOT" a tag), every time it points back to Scraps itself. For example, the Captchas or the new 403 Forbidden Error that happens because of the new browser checker that ScrapsTF has to prevent Scraps from working ENTIRELY.

I've narrowed it down to 3 possible ways that we can completely eliminate any preventions that ScrapTF may have in store for us

To avoid the 403 Forbidden Error, AKA ScrapTF not allowing you to use Scrap's browser.
1. (Least difficult to make and most realistic)Have Scraps use your main browser (Firefox or Chrome or "oPeRa Gx" since they are most compatible) to join raffles but do not show the tabs on your screen so you can continue working/playing games/watching videos/listening to music without being interrupted.

2. (Most difficult to make and least realistic) Create an entire browser dedicated to Scraps but actually make it a browser that is compatible with Firefox Extensions/Google Chrome extensions so it gains traction and possibly popularity so it doesn't get flagged by ScrapTF's browser checker.

3. (Difficult but realistic) Create a browser extension for Chrome/Firefox/OperaGX so that ScrapTF's browser checker won't flag your browser because you are using a well-known browser to use ScrapTF's website.

To avoid Captchas (Only works for Option 2 and 3!)
I would like to introduce my own interpretation of how would you bypass Captcha prompts, which is a macro recorder that records your mouse movement and the click that you make on those "I am not a robot" buttons. The more movements and clicks it records, the less chance it has to fail the Captcha.

Below are concepts I have made to make the number 3 suggestion a reality.

![image](https://user-images.githubusercontent.com/88178558/165174151-7eec678c-1791-4f39-afec-94a0a8a1be19.png)

![image](https://user-images.githubusercontent.com/88178558/165174184-e6de4fbf-ccb5-4287-9f67-2f927537b8e0.png)

![image](https://user-images.githubusercontent.com/88178558/165177522-a76c1b70-3eea-42f4-8e33-efc2b5bd26ff.png)

![image](https://user-images.githubusercontent.com/88178558/165179915-53227af5-367a-4845-b826-a9c21b18bcb9.png)

**Comment by bruhmomentobama** [comment]
@depthbomb Sorry for @ but I think it's time we ditch EXEs and move on to CRXs or XPIs

**Comment by Anonymous8623** [comment]
I have limited experience with Selenium and browser automation but I feel confident enough to say that using a Chrome extension or Selenium will probably make CAPTCHAs appear more.

Also, if you knew a thing about Google's CAPTCHAs then you would know even If Scraps 2.0 had perfect mouse movement, that's not what makes the CAPTCHAs appear in the first place.

I don't really have an idea as to where Scraps should go from here, but I hope the dev can agree using clunky browser automation is a stupid idea.

**Comment by bruhmomentobama** [comment]
> I have limited experience with Selenium and browser automation but I feel confident enough to say that using a Chrome extension or Selenium will probably make CAPTCHAs appear more.
> 
> Also, if you knew a thing about Google's CAPTCHAs then you would know even If Scraps 2.0 had perfect mouse movement, that's not what makes the CAPTCHAs appear in the first place.
> 
> I don't really have an idea as to where Scraps should go from here, but I hope the dev can agree using clunky browser automation is a stupid idea.

Then why is the captcha thing happening?

**Comment by Anonymous8623** [comment]
> > I have limited experience with Selenium and browser automation but I feel confident enough to say that using a Chrome extension or Selenium will probably make CAPTCHAs appear more.
> > Also, if you knew a thing about Google's CAPTCHAs then you would know even If Scraps 2.0 had perfect mouse movement, that's not what makes the CAPTCHAs appear in the first place.
> > I don't really have an idea as to where Scraps should go from here, but I hope the dev can agree using clunky browser automation is a stupid idea.
> 
> Then why is the captcha thing happening?

Google's CAPTCHA knows what browser your using, it's more likely to appear if you're using a non-standard browser such as Chromium or if you're using browser extensions that automate input.

**Comment by bruhmomentobama** [comment]
> > > I have limited experience with Selenium and browser automation but I feel confident enough to say that using a Chrome extension or Selenium will probably make CAPTCHAs appear more.
> > > Also, if you knew a thing about Google's CAPTCHAs then you would know even If Scraps 2.0 had perfect mouse movement, that's not what makes the CAPTCHAs appear in the first place.
> > > I don't really have an idea as to where Scraps should go from here, but I hope the dev can agree using clunky browser automation is a stupid idea.
> > 
> > 
> > Then why is the captcha thing happening?
> 
> Google's CAPTCHA knows what browser your using, it's more likely to appear if you're using a non-standard browser such as Chromium or if you're using browser extensions that automate input.

So I guess to say that Scraps is now officially obsolete?

**Comment by poopslayer4000** [comment]
> > > > I have limited experience with Selenium and browser automation but I feel confident enough to say that using a Chrome extension or Selenium will probably make CAPTCHAs appear more.
> > > > Also, if you knew a thing about Google's CAPTCHAs then you would know even If Scraps 2.0 had perfect mouse movement, that's not what makes the CAPTCHAs appear in the first place.
> > > > I don't really have an idea as to where Scraps should go from here, but I hope the dev can agree using clunky browser automation is a stupid idea.
> > > 
> > > 
> > > Then why is the captcha thing happening?
> > 
> > 
> > Google's CAPTCHA knows what browser your using, it's more likely to appear if you're using a non-standard browser such as Chromium or if you're using browser extensions that automate input.
> 
> So I guess to say that Scraps is now officially obsolete?

Most likely

**Comment by bruhmomentobama** [comment]
> > > > > I have limited experience with Selenium and browser automation but I feel confident enough to say that using a Chrome extension or Selenium will probably make CAPTCHAs appear more.
> > > > > Also, if you knew a thing about Google's CAPTCHAs then you would know even If Scraps 2.0 had perfect mouse movement, that's not what makes the CAPTCHAs appear in the first place.
> > > > > I don't really have an idea as to where Scraps should go from here, but I hope the dev can agree using clunky browser automation is a stupid idea.
> > > > 
> > > > 
> > > > Then why is the captcha thing happening?
> > > 
> > > 
> > > Google's CAPTCHA knows what browser your using, it's more likely to appear if you're using a non-standard browser such as Chromium or if you're using browser extensions that automate input.
> > 
> > 
> > So I guess to say that Scraps is now officially obsolete?
> 
> Most likely

RIP Scraps, you were good, real good! Maybe even the best!
