### ISSUE TITLE
So, due to the problem with captcha requests, I thought of 2 solutions.

### ISSUE THREAD

**Issue by Umbrozium** [depthbomb/Scraps#48]
First one would be adding an extra timer that, when a raffle prompts a captcha request, will automatically stop the program and count down (default interval being 2 hours) after which it will re-enable. The second is what I thought would be much trickier, and it's to open a new window that will show you the captcha you have to manually complete to get yourself verified.

**Comment by depthbomb** [comment]
If you are being presented with captchas when attempting to join raffles then you have set your **Join Delay** too low. The default delay values should never cause any problems.
