### ISSUE TITLE
[Feature] Linux x86 releases

### ISSUE THREAD

**Issue by Ristovski** [depthbomb/Scraps#5]
Is there a reason for providing only `arm` releases for Linux? Having `x86`/`x86-64` ones would be nice as well.

**Comment by depthbomb** [comment]
Currently only `arm` builds are available because that is the only Linux platform I can test on (since I have a Raspberry Pi 4). In the next release I can have more Linux builds but they will be untested.

**Comment by Ristovski** [comment]
Hmm, I am certain they will work on x86 as well, even on different distros.
I wonder if Github Actions has an easy way of building .NET targets, definitely something to look into.

Edit: https://docs.github.com/en/actions/guides/building-and-testing-net

**Comment by Ristovski** [comment]
Also do note that building for Linux _on_ Linux is currently impossible due to a hard-dep caused by `<TargetFramework>net5.0-windows10.0.17763.0</TargetFramework>` and (I assume) including `Microsoft.Toolkit.Uwp` and other WPF modules which are not available on Linux.

> error NETSDK1100: Windows is required to build Windows desktop applications.

**Comment by depthbomb** [comment]
Visual Studio is able to publish non-Windows versions despite the TFM and package and it successfully runs on my Raspberry Pi 4 (running Ubuntu Server 20.04)

![ss](https://i.imgur.com/VDFiF25.png)

**Comment by depthbomb** [comment]
I've created a build for `linux-x64` if you're able to test that. `x86` is not available I guess because [there are no `linux-x86` builds of the SDK.](https://github.com/dotnet/runtime/issues/31180)

[linux-x64.tar.gz](https://github.com/depthbomb/Scraps/files/6354517/linux-x64.tar.gz)

**Comment by Ristovski** [comment]
Thanks! Appears to work fine.
I'll take some time over the weekend to look into setting up Github Actions to automate builds.

**Comment by Ristovski** [comment]
Nitpick: Instead of the following, which is not only bad practice but also requires _root privileges_:
https://github.com/depthbomb/Scraps/blob/3599ab0f6adb20c6d1bf4164420c027f6653b93d/Scraps/Constants/Paths.cs#L27

perhaps something like

```C#
Path.Combine(Environment.GetFolderPath(SpecialFolder.LocalApplicationData, SpecialFolderOption.DoNotVerify), "Scraps");
```
would be better, which would put it in `/home/user/.local/share/Scraps/`, aka under `XDG_DATA_HOME`.

(might require `Directory.CreateDirectory(path)`, I didn't look into whether the directory not existing is handled anywhere)

I'll open a PR for that once I get GH Actions working, if you want, since I can't test it right now.

**Comment by depthbomb** [comment]
Will do, expect a new release either later today or tomorrow.

**Comment by FramnkRulez** [comment]
This is closed but I can't see anywhere that Linux x86 SDK builds can be downloaded?
