### ISSUE TITLE
Scrap.TF is displaying a Cloudflare challenge, Scraps cannot continue.

### ISSUE THREAD

**Issue by Dr3b3n** [depthbomb/Scraps#54]

**Comment by SunnyMenkov** [comment]
same

**Comment by depthbomb** [comment]
Nothing can be done other than just wait until the challenge is no longer shown.

**Comment by Dr3b3n** [comment]
When it should be gone ? can vpns bypass that ?

**Comment by depthbomb** [comment]
It could be a few days to a week.

**Comment by SunnyMenkov** [comment]
two weeks have passed and and it still doesn't work
