### ISSUE TITLE
cant run program

### ISSUE THREAD

**Issue by AltoidDev** [depthbomb/Scraps#57]
"you must install or update .NET to run this application"

i have the latest .NET version installed

**Comment by depthbomb** [comment]
Ensure that you have the .NET 7.0.0-rc.x _Desktop_ Runtime installed. Scraps runs on .NET 7.0 which is currently not considered the latest version as it isn't released yet. .NET 6.0 is the latest version but it is not sufficient enough to run Scraps.

**Comment by KutsaraMunmen** [comment]
How to find my cookie in scrap.tf and how do I paste it in scraps? Help please.
