### ISSUE TITLE
scraps.exe - Bad Image

### ISSUE THREAD

**Issue by BetaTester704** [depthbomb/Scraps#58]
![Screenshot 2022-12-13 145120](https://user-images.githubusercontent.com/44848633/207430632-833870cb-d4bb-4c21-921c-dc14eb2d6063.png)

Reinstalled twice, issue persists.

**Comment by depthbomb** [comment]
Intall the [.NET 7.0 Desktop Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/7.0) and see if the problem persists.
