### ISSUE TITLE
WebView2

### ISSUE THREAD

**Issue by Barmem** [depthbomb/Scraps#59]
```
Failed to initialize WebView2Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews.
 ---> System.IO.FileNotFoundException: Не удается найти указанный файл. (0x80070002)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync(String browserExecutableFolder, String userDataFolder, CoreWebView2EnvironmentOptions options)
   at Scraps.Controls.WonRafflesControl.InitializeWebViewAsync() in C:\Users\reese\Documents\Projects\.cs\Scraps\Scraps\Controls\WonRafflesControl.cs:line 56
```
I think its because i have edge browser broken, program asked to install WebView2 but windows said its already installed

**Comment by depthbomb** [comment]
Try uninstalling the WebView2 Runtime and start Scraps again.

**Comment by Barmem** [comment]
![изображение](https://user-images.githubusercontent.com/70278808/218735296-c9693f00-1af2-4ef0-8b7b-3afcf165d528.png)
says it doesnt exist

**Comment by depthbomb** [comment]
This issue seems unrelated to Scraps itself and rather with WebView2 or the WebView2 installer. This is not an issue I can address, so I suggest looking into that.
