### ISSUE TITLE
Do not enter raffles which cannot be entered by a normal user

### ISSUE THREAD

**Issue by Anon23587213** [depthbomb/Scraps#69]
**Is your feature request related to a problem? Please describe.**
The problem is that scrap staff can create a unenterable/unlisted raffle which only bots can enter and then ban anyone who enters (My 3 accounts all got banned for entering this raffle)

**Describe the solution you'd like**
Any sort of detection for situations like this that would skip the raffle

**Describe alternatives you've considered**
There is no alternative rather than to not use a bot. These raffles usually last 12 hours so scanning infrequently isn't an option

**Additional context**
Here is a bot raffle used to catch bots recently https://scrap.tf/raffles/EPPHYU

**Comment by sabo6** [comment]
seems scrap.tf started a war

**Comment by acuifex** [comment]
They likely banned based on some really old raffle. I was banned for a self-made script that i haven't used for like a year.

A possible solution could be to take the raffle html, remove or replace all changing parts, hash, and compare against known hashes. This would detect any out of ordinary changes while allowing user content.
Here's a (shitty) implementation that i've made for another website: https://github.com/acuifex/lolz-autocontest/blob/bb9c7efc3d5e443d26f6bb829f8bf16885d0fd91/solvers.py

And if they're gonna go the same way as that website, here are some recommendations:
1. Use a separate profile for each account (about:profiles in firefox)
2. Use a separate proxy/ip for each profile and don't mix them up on accident (i think this should be obvious)
3. Think about using separate user-agents if yours is too uncommon.
4. Avoid fingerprinting. I've found [this addon](https://addons.mozilla.org/en-GB/firefox/addon/no-fingerprint/) works the best, but it's still not perfect. A person told me about some "dolphin" browser, but i haven't found any info about it
5. Keep timing attacks in mind. Don't launch and stop all 5 of your accounts at the same time and shit
6. Try your best to avoid associating accounts with each other. This could include: trading items to your main (trade to a private alt and sell them instead), being friends on steam with your main, and other stuff like that
7. Try to make your accounts look somewhat real and keep some activity on them
8. Avoid polling 24/7 every couple of minutes. This could be a pretty big red flag (have a centralized server to do it for you? just throwing ideas)

**Comment by SunnyMenkov** [comment]
i was banned recently too 😭😭

**Comment by Dr3b3n** [comment]
Yeah i also got banned, damn now they're using honeypots, someone make "scrap" bypass the fake raffles.
