### ISSUE TITLE
"Could not obtain hash from raffle" on self-made raffles

### ISSUE THREAD

**Issue by ashprids** [depthbomb/Scraps#7]
Self-made raffles (specifically puzzle raffles, for some reason) are attempted to be entered by the software, returning a "Could not obtain hash from raffle" error. This spams the console with the error until it can enter the raffle (which is never). 
Would it be possible to ignore raffles made by yourself?
![image](https://user-images.githubusercontent.com/39588029/131427788-1220271d-0220-487c-959d-1bcac6717347.png)

**Comment by depthbomb** [comment]
I haven't thought of this case. I will fix this soon.
