### ISSUE TITLE
Unable to join raffle 

### ISSUE THREAD

**Issue by Xeozoid** [depthbomb/Scraps#71]
**Describe the bug**
Starting
Unable to join raffle: "Unable to enter raffle"
Waiting for next raffle, attempting to join in 4 seconds
Stopped

**To Reproduce**
idk, it works yesterday

**Additional context**
![log09768965](https://github.com/depthbomb/Scraps/assets/145290751/8f132308-9db7-44fa-b129-7963c2e34ecc)
Tried reinstalling, clearing cache, but nothing

**Comment by Dr3b3n** [comment]
Also got the same problem, any workarounds ?

**Comment by TitoWagon** [comment]
same problem here

**Comment by monoscale** [comment]
Same problem, scraps.tf just returns a message "Unable to enter raffle", so they might have a method to detect bots joining? Joining a raffle using the website works fine.

**Comment by Niximkk** [comment]
same here, fix pls

**Comment by monoscale** [comment]
The _/ajax/viewraffle/EnterRaffle_ endpoint now expects a _turnstile_token_ parameter, which is cloudfare's CAPTCHA system. Unless we have a solver this might be impossible to fix?
