### ISSUE TITLE
Stops Every So Often

### ISSUE THREAD

**Issue by JoeyDagger** [depthbomb/Scraps#8]
I would leave it running in the background and it would often stop scanning and searching for raffles with no apparent cause. I would then try to start it again, and it would return 'Stopping'. Can't seem to fix with any setting changes.

**Comment by JoeyDagger** [comment]
Screenshot of occurrence. 
![image](https://user-images.githubusercontent.com/67937427/133704799-acafb658-48af-4acf-9eae-7f26b92df8b4.png)

**Comment by depthbomb** [comment]
I am not getting this behavior, can you upload your logs file?

**Comment by JoeyDagger** [comment]
Sure, where can I find them?

**Comment by depthbomb** [comment]
Your logs should be located at `C:\Users\USERNAME\Documents\Caprine Logic\Scraps\Logs`

**Comment by JoeyDagger** [comment]
Found them, here you go.
[Scraps.2021-09.log](https://github.com/depthbomb/Scraps/files/7182019/Scraps.2021-09.log)

**Comment by depthbomb** [comment]
I was unable to replicate this problem in my time using the program since this issue was posted. If you still have the issue then try a reinstall and ensure that your internet connection is stable while it is running.

**Comment by JoeyDagger** [comment]
It is now not even starting at all. Reinstalled and stops immediately after pressing start.
